on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build MetaCall Distributabe Windows
        shell: powershell
        run: .\build.bat
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: .\metacall-tarball-win-x64.zip
